import { PDFDocument, type PDFPage, StandardFonts, rgb } from "pdf-lib"

import { getInvoiceStatusLabel } from "@/features/invoices/invoice-options"
import type { InvoiceWithCampaign } from "@/features/invoices/invoice-types"

type InvoicePdfInput = {
  creatorEmail?: string | null
  creatorName: string
  invoice: InvoiceWithCampaign
}

const pageWidth = 595
const pageHeight = 842
const margin = 56

export async function createInvoicePdf({
  creatorEmail,
  creatorName,
  invoice,
}: InvoicePdfInput) {
  const pdf = await PDFDocument.create()
  const page = pdf.addPage([pageWidth, pageHeight])
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold)

  let y = pageHeight - margin

  page.drawText("INVOICE", {
    x: margin,
    y,
    size: 28,
    font: boldFont,
    color: rgb(0.08, 0.09, 0.11),
  })

  page.drawText(creatorName, {
    x: margin,
    y: y - 34,
    size: 13,
    font: boldFont,
    color: rgb(0.08, 0.09, 0.11),
  })

  if (creatorEmail) {
    page.drawText(creatorEmail, {
      x: margin,
      y: y - 52,
      size: 10,
      font,
      color: rgb(0.38, 0.42, 0.48),
    })
  }

  y -= 96
  drawRule(page, y)
  y -= 32

  const rows: Array<[string, string]> = [
    ["Invoice number", invoice.invoice_number],
    ["Client", invoice.client_name],
    ["Issue date", formatDate(invoice.issued_date)],
    ["Due date", formatDate(invoice.due_date)],
    ["Status", getInvoiceStatusLabel(invoice.status)],
  ]

  if (invoice.paid_date) {
    rows.push(["Paid date", formatDate(invoice.paid_date)])
  }

  if (invoice.campaign) {
    rows.push([
      "Campaign",
      `${invoice.campaign.brand_name} - ${invoice.campaign.campaign_title}`,
    ])
  }

  for (const [label, value] of rows) {
    page.drawText(label, {
      x: margin,
      y,
      size: 10,
      font,
      color: rgb(0.38, 0.42, 0.48),
    })
    page.drawText(value, {
      x: 220,
      y,
      size: 11,
      font: boldFont,
      color: rgb(0.08, 0.09, 0.11),
    })
    y -= 24
  }

  y -= 18
  drawRule(page, y)
  y -= 48

  page.drawText("Amount due", {
    x: margin,
    y,
    size: 12,
    font,
    color: rgb(0.38, 0.42, 0.48),
  })
  page.drawText(formatCurrency(invoice.amount), {
    x: margin,
    y: y - 40,
    size: 30,
    font: boldFont,
    color: rgb(0.08, 0.09, 0.11),
  })

  y -= 104

  if (invoice.notes) {
    page.drawText("Notes", {
      x: margin,
      y,
      size: 12,
      font: boldFont,
      color: rgb(0.08, 0.09, 0.11),
    })
    y -= 22

    for (const line of wrapText(invoice.notes, 88)) {
      page.drawText(line, {
        x: margin,
        y,
        size: 10,
        font,
        color: rgb(0.27, 0.3, 0.35),
      })
      y -= 16
    }
  }

  page.drawText("Generated by Flowra", {
    x: margin,
    y: 42,
    size: 9,
    font,
    color: rgb(0.54, 0.58, 0.64),
  })

  return pdf.save()
}

export function createInvoicePdfFilename(invoiceNumber: string) {
  const safeInvoiceNumber = invoiceNumber
    .trim()
    .replace(/[^a-z0-9-]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()

  return `${safeInvoiceNumber || "invoice"}.pdf`
}

function drawRule(page: PDFPage, y: number) {
  page.drawLine({
    start: { x: margin, y },
    end: { x: pageWidth - margin, y },
    thickness: 1,
    color: rgb(0.9, 0.91, 0.93),
  })
}

function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-MY", {
    currency: "MYR",
    style: "currency",
  }).format(value)
}

function formatDate(value: string) {
  return new Date(`${value}T00:00:00`).toLocaleDateString("en-MY", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })
}

function wrapText(text: string, maxLength: number) {
  const words = text.trim().split(/\s+/)
  const lines: string[] = []
  let currentLine = ""

  for (const word of words) {
    const candidate = currentLine ? `${currentLine} ${word}` : word

    if (candidate.length > maxLength && currentLine) {
      lines.push(currentLine)
      currentLine = word
    } else {
      currentLine = candidate
    }
  }

  if (currentLine) {
    lines.push(currentLine)
  }

  return lines
}
