// Malaysian Food Creator Dashboard Mock Data

export const creators = [
  {
    id: "1",
    name: "Sarah Lim",
    avatar: "SL",
    handle: "@sarahlimeats",
    followers: 125000,
    engagement: 4.8,
    specialty: "Penang Street Food",
  },
  {
    id: "2", 
    name: "Ahmad Razak",
    avatar: "AR",
    handle: "@ahmadmakan",
    followers: 89000,
    engagement: 5.2,
    specialty: "Halal Fine Dining",
  },
  {
    id: "3",
    name: "Mei Ling Wong",
    avatar: "MW",
    handle: "@meilingfoodie",
    followers: 210000,
    engagement: 3.9,
    specialty: "Cafe Reviews",
  },
]

export const sponsorships = [
  {
    id: "1",
    brand: "Nasi Lemak Antarabangsa",
    campaign: "Ramadan Feast Campaign",
    status: "active",
    deliverables: ["3 Reels", "5 Stories", "1 Post"],
    postingDate: "2024-03-15",
    paymentStatus: "pending",
    amount: 8500,
    priority: "high",
    creator: "Sarah Lim",
  },
  {
    id: "2",
    brand: "Teh Tarik Place",
    campaign: "New Menu Launch",
    status: "completed",
    deliverables: ["2 Reels", "3 Stories"],
    postingDate: "2024-03-10",
    paymentStatus: "paid",
    amount: 5000,
    priority: "medium",
    creator: "Ahmad Razak",
  },
  {
    id: "3",
    brand: "Gurney Paragon",
    campaign: "Food Festival Coverage",
    status: "in-review",
    deliverables: ["5 Reels", "10 Stories", "2 Posts"],
    postingDate: "2024-03-20",
    paymentStatus: "pending",
    amount: 12000,
    priority: "high",
    creator: "Mei Ling Wong",
  },
  {
    id: "4",
    brand: "Secret Recipe",
    campaign: "Valentine Special",
    status: "negotiating",
    deliverables: ["2 Reels", "4 Stories"],
    postingDate: "2024-02-14",
    paymentStatus: "unpaid",
    amount: 6500,
    priority: "low",
    creator: "Sarah Lim",
  },
  {
    id: "5",
    brand: "Penang Char Koay Teow",
    campaign: "Heritage Food Series",
    status: "active",
    deliverables: ["4 Reels", "8 Stories", "1 Post"],
    postingDate: "2024-03-25",
    paymentStatus: "partial",
    amount: 9500,
    priority: "high",
    creator: "Ahmad Razak",
  },
  {
    id: "6",
    brand: "Boba Tea House",
    campaign: "Summer Drinks Promo",
    status: "completed",
    deliverables: ["2 Reels", "6 Stories"],
    postingDate: "2024-03-01",
    paymentStatus: "paid",
    amount: 4000,
    priority: "medium",
    creator: "Mei Ling Wong",
  },
]

export const invoices = [
  {
    id: "INV-001",
    brand: "Nasi Lemak Antarabangsa",
    amount: 8500,
    status: "pending",
    dueDate: "2024-03-30",
    issuedDate: "2024-03-01",
    category: "Sponsorship",
  },
  {
    id: "INV-002",
    brand: "Teh Tarik Place",
    amount: 5000,
    status: "paid",
    dueDate: "2024-03-15",
    issuedDate: "2024-02-20",
    paidDate: "2024-03-12",
    category: "Sponsorship",
  },
  {
    id: "INV-003",
    brand: "Gurney Paragon",
    amount: 12000,
    status: "overdue",
    dueDate: "2024-03-01",
    issuedDate: "2024-02-01",
    category: "Event Coverage",
  },
  {
    id: "INV-004",
    brand: "Freelance Photography",
    amount: 2500,
    status: "paid",
    dueDate: "2024-02-28",
    issuedDate: "2024-02-15",
    paidDate: "2024-02-25",
    category: "Photography",
  },
]

export const expenses = [
  {
    id: "EXP-001",
    description: "Camera Equipment - Sony A7IV",
    amount: 12500,
    date: "2024-02-15",
    category: "Equipment",
    taxDeductible: true,
  },
  {
    id: "EXP-002",
    description: "Monthly Adobe Creative Suite",
    amount: 250,
    date: "2024-03-01",
    category: "Software",
    taxDeductible: true,
  },
  {
    id: "EXP-003",
    description: "Restaurant Visit - Content Creation",
    amount: 450,
    date: "2024-03-05",
    category: "Business Meals",
    taxDeductible: true,
  },
  {
    id: "EXP-004",
    description: "Grab Transportation",
    amount: 180,
    date: "2024-03-10",
    category: "Transport",
    taxDeductible: true,
  },
]

export const contentPlan = [
  {
    id: "1",
    title: "Penang Laksa Ultimate Guide",
    type: "Reel",
    platform: "Instagram",
    scheduledDate: "2024-03-18",
    status: "scheduled",
    restaurant: "Sister Laksa Teluk Kumbar",
    notes: "Morning shoot, best lighting at 10am",
  },
  {
    id: "2",
    title: "Hidden Gems: Georgetown Hawker",
    type: "Carousel",
    platform: "Instagram",
    scheduledDate: "2024-03-20",
    status: "draft",
    restaurant: "Lorong Selamat Char Koay Teow",
    notes: "Need to confirm with vendor",
  },
  {
    id: "3",
    title: "Char Koay Teow Challenge",
    type: "Video",
    platform: "TikTok",
    scheduledDate: "2024-03-22",
    status: "idea",
    restaurant: "Kafe Heng Huat",
    notes: "Compare 3 famous spots",
  },
  {
    id: "4",
    title: "Best Nasi Kandar in Penang",
    type: "Reel",
    platform: "Instagram",
    scheduledDate: "2024-03-25",
    status: "scheduled",
    restaurant: "Line Clear Nasi Kandar",
    notes: "Late night crowd shots",
  },
  {
    id: "5",
    title: "Xiaohongshu: Penang Cafe Tour",
    type: "Post",
    platform: "Xiaohongshu",
    scheduledDate: "2024-03-28",
    status: "draft",
    restaurant: "China House",
    notes: "Focus on aesthetic shots",
  },
]

export const restaurants = [
  {
    id: "1",
    name: "Sister Laksa Teluk Kumbar",
    contact: "+60 12-345 6789",
    email: "contact@sisterlaksa.my",
    location: "Teluk Kumbar, Penang",
    lastContact: "2024-03-10",
    collaborations: 5,
    status: "active",
    notes: "Very responsive, best for morning shoots",
    category: "Hawker",
  },
  {
    id: "2",
    name: "Line Clear Nasi Kandar",
    contact: "+60 12-456 7890",
    email: "lineclear@email.com",
    location: "Penang Road, Georgetown",
    lastContact: "2024-03-05",
    collaborations: 3,
    status: "active",
    notes: "24 hours, great for late night content",
    category: "Restaurant",
  },
  {
    id: "3",
    name: "Tek Sen Restaurant",
    contact: "+60 12-567 8901",
    email: "teksen@restaurant.my",
    location: "Carnarvon Street, Georgetown",
    lastContact: "2024-02-20",
    collaborations: 2,
    status: "potential",
    notes: "Famous for double roasted pork, need to follow up",
    category: "Restaurant",
  },
  {
    id: "4",
    name: "Macallum Connoisseurs",
    contact: "+60 12-678 9012",
    email: "hello@macallum.com",
    location: "Gat Lebuh Macallum",
    lastContact: "2024-03-12",
    collaborations: 4,
    status: "active",
    notes: "Best coffee in Penang, great for cafe content",
    category: "Cafe",
  },
  {
    id: "5",
    name: "Jawi House Cafe Gallery",
    contact: "+60 12-789 0123",
    email: "jawi@house.my",
    location: "Armenian Street, Georgetown",
    lastContact: "2024-01-15",
    collaborations: 1,
    status: "inactive",
    notes: "Beautiful heritage building, need to reconnect",
    category: "Cafe",
  },
]

export const analyticsData = {
  overview: {
    totalRevenue: 45500,
    pendingPayments: 20500,
    activeSponsorships: 8,
    upcomingDeadlines: 5,
    avgEngagement: 4.6,
  },
  revenueByMonth: [
    { month: "Oct", revenue: 28000 },
    { month: "Nov", revenue: 35000 },
    { month: "Dec", revenue: 42000 },
    { month: "Jan", revenue: 38000 },
    { month: "Feb", revenue: 41000 },
    { month: "Mar", revenue: 45500 },
  ],
  engagementByPlatform: [
    { platform: "Instagram", engagement: 4.8, followers: 125000 },
    { platform: "TikTok", engagement: 5.2, followers: 89000 },
    { platform: "Xiaohongshu", engagement: 3.9, followers: 45000 },
  ],
  topContent: [
    { title: "Penang Laksa ASMR", views: 2500000, likes: 180000, platform: "TikTok" },
    { title: "Hidden Char Koay Teow Spot", views: 890000, likes: 75000, platform: "Instagram" },
    { title: "Nasi Kandar Mukbang", views: 650000, likes: 52000, platform: "TikTok" },
    { title: "Best Cafes in Georgetown", views: 420000, likes: 38000, platform: "Instagram" },
  ],
}

export const notifications = [
  {
    id: "1",
    type: "payment",
    title: "Payment Received",
    message: "RM 5,000 from Teh Tarik Place",
    time: "2 hours ago",
    read: false,
  },
  {
    id: "2",
    type: "deadline",
    title: "Content Deadline",
    message: "Penang Laksa Reel due tomorrow",
    time: "5 hours ago",
    read: false,
  },
  {
    id: "3",
    type: "collaboration",
    title: "New Collaboration Request",
    message: "Secret Recipe wants to discuss partnership",
    time: "1 day ago",
    read: true,
  },
]
